FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

COPY go.mod go.sum ./
RUN go mod download

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /app/main ./tools/turn

FROM alpine:latest

LABEL author="Balaji Shettigar"

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=0 /src/views /src/views
COPY --from=0 /src/assets /src/assets

EXPOSE 9050

CMD [ "/app/main" ]